# Generated by Django 2.0.4 on 2018-08-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180805_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about',
            field=models.CharField(blank=True, help_text='max of 100 characters', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/dp'),
        ),
    ]
